---
- name: Run script on remote machines
  hosts: all
  gather_facts: false
  vars:
    script_remote_dest_path: "/home/recorder"
    script_src_path: "{{ input_script_src_path }}"
    script_file_name: "{{ inputscript_file_name }}"

  tasks:
    - name: "Print if can connect"
      ansible.builtin.debug:
        msg: "Can connect"
    - name: "Copy script to remote host"
      ansible.builtin.copy:
        src: "{{ script_src_path }}"
        dest: "{{ script_remote_dest_path }}/"
        mode: "0600"
    - name: "Run script"
      ansible.builtin.command: "bash {{ remote_dest_path }}/{{ script_file_name }}"
      register: my_output
      changed_when: my_output.rc != 0
